name: test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo hack nextest run --release --all-targets --verbose --feature-powerset
    - run: cargo hack nextest run --release --all-targets --verbose --feature-powerset --rust-version
    - run: cargo hack test --doc --release --all-features --verbose
    - run: cargo hack test --doc --release --all-features --verbose --rust-version
  miri:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo +nightly miri nextest run --all-targets --all-features --verbose
  clippy:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo hack clippy --release --all-targets --verbose --feature-powerset -- --deny warnings --allow clippy::needless-doctest-main
  doc:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    env:
      RUSTDOCFLAGS: --deny warnings
    steps:
    - uses: actions/checkout@v4
    - run: cargo doc --no-deps --release --verbose --all-features
  semver:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo semver-checks --verbose
  msrv:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo msrv verify --all-features --path phylactery
    - run: cargo msrv verify --all-features --path phylactery_macro
  audit:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo audit --deny warnings
  coverage:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/magicolo/rust
    steps:
    - uses: actions/checkout@v4
    - run: cargo llvm-cov --fail-under-regions 75 --all-features --all-targets --release --verbose