name: test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        strategy:
            matrix:
                command:
                    - cargo hack nextest run --release --all-targets --verbose --feature-powerset --no-tests pass
                    - cargo hack test --doc --release --all-features --verbose
                    - cargo +nightly hack miri nextest run --all-targets --verbose --feature-powerset --no-tests pass
                    - cargo llvm-cov nextest --fail-under-regions 75 --all-features --all-targets --release --verbose
                    - cargo hack clippy --release --all-targets --verbose --feature-powerset -- --deny warnings --allow clippy::needless-doctest-main
                    - cargo hack doc --no-deps --release --verbose --all-features
                    - cargo semver-checks --verbose
                    - cargo msrv verify --all-features --path phylactery
                    - cargo msrv verify --all-features --path phylactery_macro
                    - cargo audit --deny warnings
        steps:
            - uses: actions/checkout@v6
            - run: ${{ matrix.command }}

    no_std:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/magicolo/rust
        steps:
            - uses: actions/checkout@v6
            - run: rustup target add thumbv7m-none-eabi
            - run: cargo build --target thumbv7m-none-eabi --no-default-features
            - run: cargo build --target thumbv7m-none-eabi --no-default-features --features shroud
